In [9]:
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

folders = ['Normal', 'AddWeight', 'PressureGain_constant', 'PropellerDamage_bad', 'PropellerDamage_slight']
labels = np.arange(len(folders))

data_list = []
label_list = []

for label, folder in zip(labels, folders):

    files = os.listdir(folder)

    for file in files:
        file_path = os.path.join(folder, file)
        columns_to_read = range(1, 17)
        data = pd.read_csv(file_path, header=0, nrows=180, usecols=columns_to_read)
        if data.shape[0] == 180:
            data_list.append(data)
            label_list.append(label)
        else:
            print(f'Error: {file} has {data.shape[0]} rows.')

data_array = np.array(data_list)

reshaped_data_array = data_array.reshape(-1, 16)

#global_min = reshaped_data_array.min(axis=0)
global_max = [1300, 1300, 1300, 1300, 1.5, 800, 13, 30, 20, 200, 20, 15, 20, 70, 90, 40]
normalized_data_array = (reshaped_data_array /global_max )

normalized_data_array = normalized_data_array.reshape(-1, 180, 16)

label_array = np.array(label_list).reshape(-1, 1)
encoder = OneHotEncoder(sparse_output=False)
encoded_labels = encoder.fit_transform(label_array)
print(encoded_labels.shape)
print(encoded_labels)
np.savez('testset_normalized.npz', data=normalized_data_array, labels=encoded_labels)
dataset = np.load('testset_normalized.npz')
print(dataset['data'].shape)
print(dataset['labels'].shape)
print('Normalized test set and labels saved as testset_normalized.npz')
#[1200, 1200, 1200, 1200, 0.5, 700, 12, 15, 10, 200, 20, 10, 10, 10, 30, 40]

(245, 5)
[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
(245, 180, 16)
(245, 5)
Normalized test set and labels saved as testset_normalized.npz
